/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Applications
 * OpenAPI spec version: 0.1.0
 */
import { createInstance } from "./api-instance";
export type ApplicationStatus =
  (typeof ApplicationStatus)[keyof typeof ApplicationStatus];

export const ApplicationStatus = {
  new: "new",
  in_progress: "in_progress",
  done: "done",
} as const;

export type ApplicationPriority =
  (typeof ApplicationPriority)[keyof typeof ApplicationPriority];

export const ApplicationPriority = {
  low: "low",
  normal: "normal",
  high: "high",
} as const;

export interface ApplicationCreate {
  /**
   * Application title
   * @minLength 3
   * @maxLength 120
   */
  title: string;
  /** Application description */
  description?: string | null;
  status?: ApplicationStatus;
  priority?: ApplicationPriority;
}

export interface ApplicationResponse {
  /**
   * Application title
   * @minLength 3
   * @maxLength 120
   */
  title: string;
  /** Application description */
  description?: string | null;
  status?: ApplicationStatus;
  priority?: ApplicationPriority;
  /** Unique application identifier */
  id: number;
  created_at: string;
  updated_at: string;
}

export type ApplicationSortBy =
  (typeof ApplicationSortBy)[keyof typeof ApplicationSortBy];

export const ApplicationSortBy = {
  created_at: "created_at",
  priority: "priority",
} as const;

export interface ApplicationUpdate {
  status: ApplicationStatus;
}

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface PaginatedResponseApplicationResponse {
  items: ApplicationResponse[];
  total: number;
  page: number;
  size: number;
  pages: number;
}

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const SortOrder = {
  asc: "asc",
  desc: "desc",
} as const;

export interface UserLoginSchema {
  username: string;
  password: string;
}

export type GetApplicationsApiApplicationsGetParams = {
  status?: ApplicationStatus | null;
  priority?: ApplicationPriority | null;
  search?: string | null;
  sort_by?: ApplicationSortBy;
  sort_order?: SortOrder;
  page?: number;
  size?: number;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get Applications
 */
export const getApplicationsApiApplicationsGet = (
  params?: GetApplicationsApiApplicationsGetParams,
  options?: SecondParameter<
    typeof createInstance<PaginatedResponseApplicationResponse>
  >,
) => {
  return createInstance<PaginatedResponseApplicationResponse>(
    { url: `/api/applications`, method: "GET", params },
    options,
  );
};

/**
 * @summary Create Application
 */
export const createApplicationApiApplicationsPost = (
  applicationCreate: ApplicationCreate,
  options?: SecondParameter<typeof createInstance<ApplicationResponse>>,
) => {
  return createInstance<ApplicationResponse>(
    {
      url: `/api/applications`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: applicationCreate,
    },
    options,
  );
};

/**
 * @summary Get Application
 */
export const getApplicationApiApplicationsApplicationIdGet = (
  applicationId: number,
  options?: SecondParameter<typeof createInstance<ApplicationResponse>>,
) => {
  return createInstance<ApplicationResponse>(
    { url: `/api/applications/${applicationId}`, method: "GET" },
    options,
  );
};

/**
 * @summary Update Application Status
 */
export const updateApplicationStatusApiApplicationsApplicationIdPatch = (
  applicationId: number,
  applicationUpdate: ApplicationUpdate,
  options?: SecondParameter<typeof createInstance<ApplicationResponse>>,
) => {
  return createInstance<ApplicationResponse>(
    {
      url: `/api/applications/${applicationId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: applicationUpdate,
    },
    options,
  );
};

/**
 * @summary Delete Application
 */
export const deleteApplicationApiApplicationsApplicationIdDelete = (
  applicationId: number,
  options?: SecondParameter<typeof createInstance<void>>,
) => {
  return createInstance<void>(
    { url: `/api/applications/${applicationId}`, method: "DELETE" },
    options,
  );
};

/**
 * @summary Login
 */
export const loginApiAuthLoginPost = (
  userLoginSchema: UserLoginSchema,
  options?: SecondParameter<typeof createInstance<unknown>>,
) => {
  return createInstance<unknown>(
    {
      url: `/api/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: userLoginSchema,
    },
    options,
  );
};

/**
 * @summary Root
 */
export const rootGet = (
  options?: SecondParameter<typeof createInstance<unknown>>,
) => {
  return createInstance<unknown>({ url: `/`, method: "GET" }, options);
};

/**
 * @summary Health Check
 */
export const healthCheckHealthGet = (
  options?: SecondParameter<typeof createInstance<unknown>>,
) => {
  return createInstance<unknown>({ url: `/health`, method: "GET" }, options);
};

export type GetApplicationsApiApplicationsGetResult = NonNullable<
  Awaited<ReturnType<typeof getApplicationsApiApplicationsGet>>
>;
export type CreateApplicationApiApplicationsPostResult = NonNullable<
  Awaited<ReturnType<typeof createApplicationApiApplicationsPost>>
>;
export type GetApplicationApiApplicationsApplicationIdGetResult = NonNullable<
  Awaited<ReturnType<typeof getApplicationApiApplicationsApplicationIdGet>>
>;
export type UpdateApplicationStatusApiApplicationsApplicationIdPatchResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof updateApplicationStatusApiApplicationsApplicationIdPatch
      >
    >
  >;
export type DeleteApplicationApiApplicationsApplicationIdDeleteResult =
  NonNullable<
    Awaited<
      ReturnType<typeof deleteApplicationApiApplicationsApplicationIdDelete>
    >
  >;
export type LoginApiAuthLoginPostResult = NonNullable<
  Awaited<ReturnType<typeof loginApiAuthLoginPost>>
>;
export type RootGetResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>;
export type HealthCheckHealthGetResult = NonNullable<
  Awaited<ReturnType<typeof healthCheckHealthGet>>
>;
